import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'index', // Trang chủ tài liệu (docs/index.mdx)
    {
      type: 'category',
      label: 'Trung Tâm Hướng Dẫn JEGA',
      link: {
        type: 'generated-index',
        title: 'Trung Tâm Hướng Dẫn JEGA',
        description: 'Khám phá các hướng dẫn chi tiết về cách sử dụng phần mềm JEGA, từ cơ bản đến nâng cao.',
        keywords: ['hướng dẫn', 'JEGA', 'tài liệu'],
        slug: '/category/trung-tam-huong-dan'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'trung-tam-huong-dan',
        },
      ],
    },
    /*
    {
      type: 'category',
      label: 'Bộ Sưu Tập JEGA',
      link: {
        type: 'generated-index',
        title: 'Bộ Sưu Tập JEGA',
        description: 'Khám phá các bộ sưu tập thiết kế mẫu từ JEGA.',
        slug: '/category/bo-suu-tap-jega'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'jega-collection',
        },
      ],
    },
    */
    /*
    {
      type: 'category',
      label: 'Tham Khảo API',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api-reference',
        },
      ],
    },
    */
    {
      type: 'category',
      label: 'Tài Liệu Thiết Yếu',
      link: {
        type: 'generated-index',
        title: 'Tài Liệu Thiết Yếu',
        description: 'Các tài liệu thiết yếu và hướng dẫn cơ bản.',
        slug: '/category/tai-lieu-thiet-yeu'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'essentials',
        },
      ],
    },
    {
      type: 'category',
      label: 'Hướng Dẫn Chung',
      items: [
        'IMPLEMENTATION_GUIDE',
        'SEO-guide',
      ],
    },
    {
      type: 'category',
      label: 'Tài Liệu Kỹ Thuật & Quy Trình',
      items: [
        'KB-document',
        'KB-template',
        'Task-checklist',
        'Videotask-checklist',
        'system_prompt_customer_success_jega_vn',
        'system_prompt_market_research_jega_vn',
      ],
    },
  ],
};

export default sidebars;
